var snake = [], particles = [], foods = [], floatingTexts = [], projectiles = [], aiSnakes = [];
var velocity = { x: 0, y: 0 }, nextVelocity = { x: 0, y: 0 };
var score = 0, enemiesKilled = Number(localStorage.getItem('snakeEnemiesKilled')) || 0, killStreak = 0, bossSpawnTimestamp = 0, growthBuffer = 0, prestigeLevel = 0;
var ownedPets = JSON.parse(localStorage.getItem('snakeOwnedPets')) || [];
var activePetIds = JSON.parse(localStorage.getItem('snakeActivePets')) || [];
var petInstances = [];
var renderLoopId, isPaused = false, isGameOver = false, speed = 110;
var camera = { x: 0, y: 0 }, TILE_COUNT_X = 20, TILE_COUNT_Y = 20;
var playerLevel = Number(localStorage.getItem('snakePlayerLevel')) || 1;
var currentXp = Number(localStorage.getItem('snakeXp')) || 0;
var coins = Number(localStorage.getItem('snakeCoins')) || 0;
var souls = Number(localStorage.getItem('snakeSouls')) || 0;
var highScore = Number(localStorage.getItem('snakeHighScore')) || 0;
var rebirthPoints = Number(localStorage.getItem('snakeRP')) || 0;
var rebirthCount = Number(localStorage.getItem('snakeRebirthCount')) || 0;
var upgrades = JSON.parse(localStorage.getItem('snakeUpgrades')) || {};
var prestigeUpgrades = JSON.parse(localStorage.getItem('snakePrestigeUpgrades')) || { permGold1: 0, permGold2: 0, permSouls1: 0, permSouls2: 0, permRP1: 0, permRP2: 0, permXp: 0 };
var slayerUpgrades = JSON.parse(localStorage.getItem('snakeSlayerUpgrades')) || { maxHearts: 0, maxStamina: 0, staminaRegen: 0 };
var currentHearts = 1, currentStamina = 100, isSprinting = false, isExhausted = false;
var staminaRegenTimestamp = 0, isPlayerInvulnerable = false, playerInvulnerabilityTime = 0, shakeEndTime = 0, auraTimer = 0;
var soundEnabled = localStorage.getItem('snakeSound') !== 'false';
var particlesEnabled = localStorage.getItem('snakeParticles') !== 'false';
var showEatRange = localStorage.getItem('snakeShowRange') !== 'false';
var glowEnabled = localStorage.getItem('snakeGlow') !== 'false';
var brightnessLevel = parseFloat(localStorage.getItem('snakeBrightness')) || 1.0;
var lowQualityMode = localStorage.getItem('snakeLowQuality') === 'true';
var currentLanguage = localStorage.getItem('snakeLanguage') || 'en';
var audioCtx, touchStartX = 0, touchStartY = 0;
TILE_COUNT_X = 20 + playerLevel;
TILE_COUNT_Y = 20 + playerLevel;
if (typeof upgrades.foodCount === 'undefined') upgrades.foodCount = 0;
if (typeof upgrades.scoreMult === 'undefined') upgrades.scoreMult = 0;
if (typeof upgrades.doublePoints === 'undefined') upgrades.doublePoints = 0;
if (typeof upgrades.xpMult === 'undefined') upgrades.xpMult = 0;
if (typeof upgrades.growthBoost === 'undefined') upgrades.growthBoost = 0;
if (typeof upgrades.eatRange === 'undefined') upgrades.eatRange = 0;
if (typeof upgrades.luckBoost === 'undefined') upgrades.luckBoost = 0;
if (typeof upgrades.soulsMult === 'undefined') upgrades.soulsMult = 0;
if (typeof upgrades.soulsExp === 'undefined') upgrades.soulsExp = 0;
if (typeof prestigeUpgrades.permGold1 === 'undefined') prestigeUpgrades.permGold1 = 0;
if (typeof prestigeUpgrades.permGold2 === 'undefined') prestigeUpgrades.permGold2 = 0;
if (typeof prestigeUpgrades.permXp === 'undefined') prestigeUpgrades.permXp = 0;
if (typeof prestigeUpgrades.permRP1 === 'undefined') prestigeUpgrades.permRP1 = 0;
if (typeof prestigeUpgrades.permRP2 === 'undefined') prestigeUpgrades.permRP2 = 0;
if (typeof prestigeUpgrades.permSouls1 === 'undefined') prestigeUpgrades.permSouls1 = 0;
if (typeof prestigeUpgrades.permSouls2 === 'undefined') prestigeUpgrades.permSouls2 = 0;
if (typeof slayerUpgrades.maxHearts === 'undefined') slayerUpgrades.maxHearts = 0;
if (typeof slayerUpgrades.maxStamina === 'undefined') slayerUpgrades.maxStamina = 0;
if (typeof slayerUpgrades.staminaRegen === 'undefined') slayerUpgrades.staminaRegen = 0;
if (typeof slayerUpgrades.gold1 === 'undefined') slayerUpgrades.gold1 = 0;
if (typeof slayerUpgrades.gold2 === 'undefined') slayerUpgrades.gold2 = 0;
if (typeof slayerUpgrades.rp1 === 'undefined') slayerUpgrades.rp1 = 0;
if (typeof slayerUpgrades.rp2 === 'undefined') slayerUpgrades.rp2 = 0;
if (typeof slayerUpgrades.souls1 === 'undefined') slayerUpgrades.souls1 = 0;
if (typeof slayerUpgrades.souls2 === 'undefined') slayerUpgrades.souls2 = 0;
if (typeof slayerUpgrades.infiniteStamina === 'undefined') slayerUpgrades.infiniteStamina = 0;
var canvas, ctx, minimapCanvas, minimapCtx, scoreElement, highScoreElement, coinsElement, rpElement, levelElement;
var menuOverlay, shopOverlay, guideOverlay, settingsOverlay, rebirthOverlay, slayerShopOverlay;
var startBtn, shopBtn, rebirthMenuBtn, guideBtn, settingsBtn, resetBtn, slayerShopBtn;
var closeShopBtn, closeRebirthBtn, doRebirthBtn, closeGuideBtn, closeSettingsBtn, closeSlayerShopBtn;
var toggleSoundBtn, toggleParticlesBtn, toggleRangeBtn, toggleGlowBtn, toggleBrightnessBtn, toggleQualityBtn;
var langEnBtn, langArBtn;
var progressFill, progressText, xpFill, xpText;
